### ISSUE TITLE
Serve fonts from local server folders, not google fonts

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#103]
It might be slower but I think it is better to include the fonts in our files

**Comment by adamblake** [comment]
Maybe we could use local files as a back up? By now, many people will have the popular google fonts cached. I can set it up so that we use a local copy if Google is unavailable

**Comment by adamblake** [comment]
This should clear this up. Serving from Google will probably always be faster, but when Google is down/firewalled/unavailable the fonts will be served from the host.

**Comment by gikeymarcia** [comment]
solved by 090cc4f45a5cc32a733f397f415740300f5fa539
