### ISSUE TITLE
Randomize the options on the Instructions readcheck

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#106]
People will quickly learn the third option is the default correct and it would be nice to have the javascript randomize the order of the `<li>` options on `Experiment/Instructions.php`

**Comment by TysonKerr** [comment]
Perhaps just randomize the last 2? I thought that part of the test was simply checking if they clicked the first option, and go in order.

**Comment by gikeymarcia** [comment]
I treated it as a check to make sure they read the instructions.  If they aren't able to answer correctly then they didn't ready closely enough.

**Comment by TysonKerr** [comment]
Right, but if the correct answer is the top option, then people just clicking through won't be detected. Of course, that still wouldn't catch lucky guessers.

**Comment by gikeymarcia** [comment]
ah, i see what you mean.  My science heart wants true random but I can see how it could play into the hands of the lazy.  I suppose randomize everything but the first choice is sufficient.
