### ISSUE TITLE
Inconsistent precaching

### ISSUE THREAD

**Issue by adamblake** [gikeymarcia/Collector#109]
Precaching is currently inconsistent across trials. I believe what we would like is:
* Hide *everything* until $(document).ready fires
* Show the trial until the trial time runs out or the form is submitted
* Hide *everything* and go to next trial

In some cases the last part fails and, for instance, the submit button is hidden but the cue or prompt remains on screen. I think that the general idea amongst us has been to move all of the .precache classes out of the trial types and just hide the page on a global level.

Items to resolve:
* change .precache to "visibility: hidden" instead of "display: none"
* remove .precache from trial types
* add .precache globally for all trials

**Comment by adamblake** [comment]
Created branch 109-precache

**Comment by gikeymarcia** [comment]
The thing you want to precache is the `body > form` or you can use it's ID `content`. The way `dev` is structured the entire display of a trial is contained with `#content` so hiding that element gets rid of the need for designating some elements of the page as `.precache`

Aside from this, each page should also be loading the stimuli for the following trial although @TysonKerr tells me he is working on a new scheme for handling precaching throughout the experiment.

**Comment by adamblake** [comment]
I'm looking at it, and I guess I misunderstood when talking to @TysonKerr earlier. It looks like this has already been resolved. Correct me if I'm wrong...

**Comment by TysonKerr** [comment]
It looks like we are making the form visible/invisible on experiment.php, which should be functionally the same as using the body. Since the trials during experiment.php are the ones that we care about, in terms of precaching, it looks like things are good to go.

**Comment by TysonKerr** [comment]
actually, we should make the change so that precaching affects the whole body. It looks weird when the Final Question moves down after the question disappears.

**Comment by gikeymarcia** [comment]
Couldn't we just move the Final Question inside the form?

**Comment by adamblake** [comment]
Yeah I have to agree with @gikeymarcia, seems more like an issue that we should just solve when we figure out the Final Questions / Demographics mess. On the docket for tomorrow?
