### ISSUE TITLE
Settings as INIs

### ISSUE THREAD

**Issue by adamblake** [gikeymarcia/Collector#110]
Settings are currently read as multiple global variables and are set in a PHP file. The file itself would be more readable as an INI, and we can clear up the global namespace clutter by reading them in as one array or class.

**Comment by TysonKerr** [comment]
Files to target:
Experiment/Settings.php
Code/fileLocations.php

Maybe if file locations is a class, then it can also handle things like preparing the entire pathway, after we use the ini file to provide all the segments? For example, after we provide "Images/" as the folder for images, then show() could ask the file locations object for the path to images, and get a string that correctly navigates to the root folder and then into Experiments/Common/Images, and then use the result. 

Also, perhaps we shouldn't provide the trailing slash for directories, and instead have the settings arranged in a way that you can clearly see what is a filename and what is a folder. I think a lot of php functions that return a directory (like dirname()) don't return a trailing slash, so to be consistent with those functions, we should expect to add our own directory separator to the returned string.

**Comment by gikeymarcia** [comment]
https://github.com/gikeymarcia/Collector/issues/99 is relevant to this issue.

**Comment by gikeymarcia** [comment]
https://github.com/gikeymarcia/Collector/issues/98 is also relevant.

**Comment by adamblake** [comment]
So I've been thinking and rethinking and rethinking again how to handle FileLocations and I was wondering what you guys think about this method of accessing what I'm calling 'named routes':

Given INI settings:
```
; This section sets the names of the main folders used in Collector
; The values should be values or relative paths from the root directory
[root_directories]
data_folder = Data
code_folder = Code
expt_folder = Experiment
tool_folder = Tools

; This section sets the subfolder and file locations in the expt_folder
; The values should be values or relative paths from the expt_folder directory
[expt]
ineligibile = Ineligible
stim_files  = ../Stimuli 
proc_files  = Procedure


etc., etc., etc.
```

The PHP:
```
$_paths->expt;                 // returns "path/to/Experiment"
$_paths->expt->stim_files;  // returns "path/to/Experiment/../Stimuli
```
This allows for non-unique filenames and directories as long as they are not at the root level, but you do have to remember where the file or directory is relative to the ```root_directories```. It's also possible to add a unique named route: ```$_paths->add('unique_name', 'path/to/wherever');```

**Comment by adamblake** [comment]
Just to give an update, the only thing left is to change all the references in the rest of the files now. Also, @TysonKerr, I added in some functions for generating URLs and relative paths that are easy to access:
```
$_FILES->images;                             // returns "C:/root/path/to/images"
$_FILES->images->toUrl();                    // returns "http://base_url/path/to/images"
$_FILES->images->relativeTo($_FILES->root);  // returns "./path/to/images"

**Comment by adamblake** [comment]
Should be ready to go. I tested what I could think of testing and everything seems to be running smoothly. I'll leave this up in case anyone has changes they want to make/suggest

**Comment by gikeymarcia** [comment]
Why do some of the lines in the BasicConfig.ini file terminate with a `;` but other lines do not? It looks like no `;` is the norm until line 26 then it switches to mostly `;` terminated.  I can see that semicolons are used for comments but is there a reason they should or shouldn't be used to terminate lines?

If they're not 100% required somewhere it seems simpler to leave them all without a `;` so we don't nee to explain to people that sometimes it is used for comments and other times it is used to terminate a variable declaration.

**Comment by adamblake** [comment]
Because copy/paste. Fixed: f07cf35f61ce1dfa3baffd318846f217d6bcf7a6

**Comment by TysonKerr** [comment]
Looks pretty cool to me. In initiateCollector.php, is there a reason that the fileLocations.ini file is parsed first, and then sent to the FileLocations class, rather than having the __construct() function both calculate $_rootF and parsing the ini file?

**Comment by adamblake** [comment]
Yeah --- if we ever change away from INI files, it makes more sense to change the way we parse the configs than it does to change the way that FileLocations handles different configs. This way FileLocations is relatively independent from Parse methods and only requires an array of parameters. Funnily enough, I actually had it the way you are suggesting up until I was going back over the code and thought of the above...

**Comment by gikeymarcia** [comment]
solved by lots of code, it is all over the place.
