### ISSUE TITLE
error checking with files

### ISSUE THREAD

**Issue by TysonKerr** [gikeymarcia/Collector#113]
Couple of things to check for at the beginning of the experiment:

In getFromFile(), the file headers should be scanned for duplicate headers (after trimming). If found, cause horrendous failure to occur.

Also in getFromFile(), check for empty columns. Sometimes, after clearing contents of a column, it still exists in the file as a bunch of blank cells, which causes errors in experiment.php when createAlias tries to make a variable `$` .

Finally, since all columns are getting aliased in experiment.php, we should also check if the stimuli and the procedure file have overlapping contents. Currently, if both files have a `Notes` column, I believe the stimuli values will be used, but this should just be prevented, rather than made ambiguous.

**Comment by gikeymarcia** [comment]
This is solved in login rewrite. The only columns we allow to overlap are the shuffle columns.
