### ISSUE TITLE
javascript Collector.experiment.trialType

### ISSUE THREAD

**Issue by TysonKerr** [gikeymarcia/Collector#114]
I have several trial types that use this to run a script at the start of the trial:
```javascript
COLLECTOR.experiment.<?= $trialType ?> = function() {

}
```
I think this is more complicated than it needs to be, although its cool that the data action/controller allows for this. But I think we should simplify this, so that it just needs to be
```javascript
COLLECTOR.begin = function() {}
```
and we can overwrite that function with whatever script we need. After precache, run the script. That way, if someone makes a trial type that uses a hyphen in its name, it doesnt cause a crash when it tries to parse
``` javascript
COLLECTOR.experiment.trial-type = function() {}
```
which is another weird thing to explain to people, since the rest of the trial type works fine. In fact, if people are using separate custom js files, it might just be best to have the function unattached to the COLLECTOR object, since I'm not sure if async loading of scripts will ever cause a problem. So, something like 
```javascript
CollectorBegin = function() {}
```
and then in the collector.js script
```javascript
if (typeof window["CollectorBegin"] === "function") window["CollectorBegin"]();
```
Also, if you are using a script.js file in a trial type, it can't use php to echo out the trialType name, so this would let people actually separate their files into html, css, and js.

**Comment by adamblake** [comment]
Looks like a great fix, Tyson --- I say go for it

**Comment by gikeymarcia** [comment]
right now I'm calling this trialBegin = function() {...} and it is in the current dev branch. Good to close this?
