### ISSUE TITLE
better text replace for text column variable replacement

### ISSUE THREAD

**Issue by TysonKerr** [gikeymarcia/Collector#115]
right now, the text column can turn something like `here is an image: $cue` into `here is an image: images/picture.png`. Instead of just replacing with the $cue, we should use `show()` to replace with the actual image, so that it becomes `here is the image: <img src="images/picture.png">`

**Comment by TysonKerr** [comment]
Another idea for text would be the ability to reference files. For trial types like instructions, where you want a large block of styled html, it can be difficult to write that into a spreadsheet cell. Instead, if you could simply put `html/instructions1.html`, and then place that file in the `Experiment/` folder, then large blocks of instructions would be easier to write.

**Comment by gikeymarcia** [comment]
solved in JITexp
