### ISSUE TITLE
make variable names in experiment a little less likely to conflict with columns

### ISSUE THREAD

**Issue by TysonKerr** [gikeymarcia/Collector#116]
I tried making a column called "Name" which didn't get converted to `$name` because I use that variable in the actual aliasing function. I'll try making the variable names in `experiment.php` something that doesn't sound like a column name.

**Comment by gikeymarcia** [comment]
solved, mostly... sort of, by @TysonKerr because of using camel case with Experiment.php variables and extracting using snake case (e.g., "this_is_snake_case")

**Comment by gikeymarcia** [comment]
solved in branch JITexp
