### ISSUE TITLE
$_FILES not working in windows

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#119]
Looking at newest 'dev' branch I'm not able to run on WAMPserver.

At `index.php` my header URLS are pointing to the right places. For example, the css url is `http://localhost:8080/col/Code/css/global.css`

When I attempt to login at `login.php` the css url is in the header as `http://localhost:8080/col/Code/login.php?Username=mikey&Condition=0/Code/css/global.css`

Not sure what has gone wrong. @adamblake  @TysonKerr , any clue? Looks like this problem goes all the way back to the creation of the `FileLocations` class.

Last known good state is 123687637c41d07dde26d9ce0f51780d92b7af9d

**Comment by adamblake** [comment]
Yeah I need to change it so that it doesn't include the Get statement in the URL when getting files, only when showing pages

**Comment by TysonKerr** [comment]
@adamblake, it's a really hard bug to replicate. Mikey and I were both running it on wamp, but only he was ever able to see the bug. And it wouldnt happen on every page, but when it did, it didnt necessarily have a get request, like done.php or Tools/index.php. Looking at the fileLocations class, there was a section in determineBaseUrl() where you get the request_uri and pull off the trailing path past the root directory, but for some reason it wasnt working for Mikey. So, mine would take the request_uri of "/dev/Tools" and trim it to "/dev", but for Mikey, this trimming wouldn't happen. Mikey and I couldn't figure out any differences in our setups that would cause this, except he was testing on Windows 10

**Comment by adamblake** [comment]
I think I know what the problem is, but I can't remember what it is... I can remember how to make myself remember though, so I've got that going for me, which is nice...

**Comment by gikeymarcia** [comment]
The problem is that I'm running from an aliased folder. The problem isn't "solved" but we do know why it is happening.
