### ISSUE TITLE
Proceed to post trial only if participant enters data on previous trial

### ISSUE THREAD

**Issue by lukechurchill** [gikeymarcia/Collector#164]
Hi!

This isn't an issue so much as a question about functionality. I'd like to implement a post trial if and only if a participant enters data on the previous trial. Is there any way you can point me in the right direction on implementing this?

Best,

Luke

**Comment by TysonKerr** [comment]
If you are using the master branch, during every trial there is a variable called `$currentTrial` which holds the information about the current procedure row that is being run, all post trials included. This variable is an array, containing a `Stimuli`, `Procedure`, and `Response` sub-array. If the main trial stores responses in the typical fashion (by saving it as 'Response'), then you should be able to find this response inside `$currentTrial['Response']['Response']`. So, you can add something like the following script to the top of your post trial type:

``` php
<?php

if (empty($currentTrial['Response']['Response'])) {
    ?><script>
        $(window).load(function() { $("form").submit(); });
    </script><?php
}

```

This would essentially be saying:
If the current trial doesn't have a "Response" saved in its response array, or if that value is an empty string, tell the current trial to automatically submit itself as soon as it starts.

**Comment by lukechurchill** [comment]
Thank you!

**Comment by lukechurchill** [comment]
Follow up question,

I have a second post trial that I'd like to appear depending on whether or not there is a response in the first post trial. I've been playing around with the solution you posted above, but I can't seem to get it to work for this new situation. What should I do?

Thanks,

Luke

**Comment by TysonKerr** [comment]
To start, I think you can just have the post 2 trial type do a var_dump() of $currentTrial, and you can see if any flags appear that seem helpful. But in the general case, I would imagine that the post trial also saves its response as "Response", so you would be looking for 

``` php
$currentTrial['Response']['post1_Response']
```

to check the post trial 1 response. If you are collecting a different response in your post 1 trial, such as a JOL, then just look for something with a prefix `post1_`, like `post1_JOL`.

**Comment by lukechurchill** [comment]
So the variable in question is output in data as Exp_Response*post1_JOL, but when I use the above code the trial continues to show up. 

Here's the code I have right now:
<?php

if (empty($currentTrial['Response']['post1_JOL'])) {
    ?><script>
        $(window).load(function() { $("form").submit(); });
    </script><?
}
Sorry to bother you again!

Luke

**Comment by lukechurchill** [comment]
Sorry, the script code you provided above is also included, I'm just unsure how to post that code in these comments.

**Comment by TysonKerr** [comment]
Interesting. When I tried modifying the instruct trial type to include the code

``` php
    if (empty($currentTrial['Response']['post1_JOL'])) {
        ?><script>
            $(window).load(function() { $("form").submit(); });
        </script><?php
    }
```

and used it as post trial 2, after a JOL, the trial only appeared if I entered something into the JOL input during post trial 1.

One thing that could be happening is that you have two copies of the trial type, and you are modifying the version that the Collector isn't using. If a trial type exists in both `Code/TrialTypes` and `Experiment/TrialTypes`, then the version inside `Experiment/TrialTypes` is used, so if you are modifying the one found in `Code/`, the extra code wont be used.

One test would be to simply change the added code to be

``` php
<?php

var_dump(empty($currentTrial['Response']['post1_JOL']));
```

This should put something saying "true" on the screen when the post 2 trial should be skipped, and put "false" on the screen when the post trial should be shown. If instead, nothing is showing up, then you are modifying a file that the Collector isnt using at that point, and you need to find the correct file.

**Comment by lukechurchill** [comment]
Hi,

I've gotten the code you've given me to work with both the Instruct trial type and the Copy trial type. However, the post 2 trial type I need to implement in the actual trial type is a likert, and in that trial type the code seems to have no effect at all. Sorry to bother you again.

Best,

Luke

**Comment by TysonKerr** [comment]
Hmm. I tried it with a likert trial as well, and it seemed to be skipping the trial correctly. If you instead modify the likert trial type to look like this:

``` php
<?php

if (empty($currentTrial['Response']['post1_JOL'])) {
    echo 'empty response, should skip';
} else {
    echo 'filled response, should run trial';
}

```

do you get the correct message during the trial type?

**Comment by lukechurchill** [comment]
I got it to work. Thanks, sorry to bother you!

Best,

Luke
