### ISSUE TITLE
Update text in condition 1

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#32]
Definitely out of date by now.  Update to reflect new realities

**Comment by adamblake** [comment]
Note: I'm assuming this is the tutorial condition, "How to use Collector" (or something like that). Is this right?

**Comment by TysonKerr** [comment]
Well, a lot of the pre-existing conditions are supposed to act as tutorials, and we will need to update them all as we go along. For example, the shuffling demos will need to be updated when Mikey's new shuffling system goes in, and my shuffles already exist but are totally undocumented. So, this issue could probably be expanded to update all the basic procedure and stimuli files that come with the collector.

**Comment by gikeymarcia** [comment]
How about building all of these tutorial files into a `/Tools/` tool then just putting a base Stimuli and Procedure file into each folder that each contain all of the columns and different examples of the types of values you can set.

**Comment by adamblake** [comment]
I like this best too



On Jan 23, 2015, at 04:02, Mikey Garcia <notifications@github.com> wrote:

How about building all of these tutorial files into a /Tools/ tool then just putting a base Stimuli and Procedure file into each folder that each contain all of the columns and different examples of the types of values you can set.

**Comment by gikeymarcia** [comment]
Current solution is to make demos for each trial type. Allison and Emanuel are cranking away on it and thus, this issue is dead. Bang! Headshot.
