### ISSUE TITLE
Video trial type

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#69]
up to you

**Comment by gikeymarcia** [comment]
I'm thinking instead of a `Video` trial type we'd be better served by making a `YouTube` trial type.  I was looking over the Youtube API page (https://developers.google.com/youtube/iframe_api_reference) and it seems very promising.  Under the Getting Started section there is even sample code that "creates an embedded player that will load a video, play it for six seconds, and then stop the playback".

I would imagine we could get a lot more functionality using these built in tools for YouTube videos than if we tried to build our own thing.

**Comment by gikeymarcia** [comment]
Forgot to mention, this embed will launch an HTML5 version of the youtube player so it can be controlled with javascript.  YouTube has recently switched over completely to HTML5 for video playback so I think it is fairly safe to assume a very high percentage of the web is on a browser that can handle HTML5 youtube videos.

**Comment by TysonKerr** [comment]
I have a version of both, where one can use videos that you have on your server, and another uses a youtube embed. Perhaps I can merge them into one, and have the trial type detect if they have provided a url for embedding or an actual video file.

**Comment by gikeymarcia** [comment]
Checkout this JS script that is designed to add <video> and <audio> support for browsers that aren't HTML5 savvy.

http://mediaelementjs.com/

**Comment by adamblake** [comment]
Created a new branch '69-video-trials' to resolve this issue. Right now it appears we are trying to do the following:
* Add support for YouTube videos
  * Default to HTML5
  * Provide a browser fallback, possibly using mediaelementjs.com or some other solution
* Add support for user supplied videos
* Trial type should be named 'video' and incorporate timing in the same way other trials do

**Comment by gikeymarcia** [comment]
Instead of writing code to figure out if the source is local or youtube why don't we just make two different trial types? I imagine it is much simpler, from a code perspective, to have `YouTube` and `LocalVideo` trial types. If the end user can't be bothered to think about where their videos are should we really waste coding time trying to solve something that could just as easily be handled by the user having even the slightest clue about what they are doing.

It seems easier to maintain these two sets of code separately than putting them together just because people don't want to think.

**Comment by adamblake** [comment]
I think that just intuitively it would make more sense to say I have a "video" and "this is where it is." I can just do a regex to figure out if we are looking at a YouTube, Vimeo, or local file and then apply the appropriate settings accordingly. I already have the YouTube settings from helping a 121 group project, so I just need to figure out Vimeo and local files (which shouldn't take more than a few minutes really).

**Comment by adamblake** [comment]
Okay so here's the deal with start and stop times. 

For YouTube it is easy to handle and I'll pop in this as a settings option where you can use "start-time=120; stop-time=140". For Vimeo, start times are easy, but stop times will probably require using their Javascript API, which adds weight and time to finishing this up. I haven't yet looked into how to manipulate the iframe HTML5 player for local files yet.

**Comment by gikeymarcia** [comment]
Sounds like you're making good progress here. I'll leave all video related decision making in your hands.

**Comment by adamblake** [comment]
Consensus from meeting: local video trial type and YouTube trial type

**Comment by gikeymarcia** [comment]
And I'd say `YouTube` is a high priority Collector 2.0 feature while `local video` is a 2.1 feature

**Comment by gikeymarcia** [comment]
@TysonKerr do you think you can bridge your work with Adam's branch to complete `YouTube` on your own? This would free up some of the burden on @adamblake

**Comment by TysonKerr** [comment]
I can take care of this, but mostly its a matter of splitting Adam's function into youtube/local video, and adding the 2 parameters starttime and endtime to youtube videos. Very little of my original type is actually needed.

**Comment by gikeymarcia** [comment]
Mind dump from meeting:
`Max Time` cannot be a set # of seconds
if an `End Time` is specified in the `Stimuli.csv` file then the page will submit when the end time is reached
If no `End Time` is specified the `Next` button will appear when the video ends.
if no `Start Time` is specified in the `Stimuli.csv` file then the video will begin at 0s 

Chime in if this doesn't sound right.

**Comment by TysonKerr** [comment]
I ended up keeping Adam's trial type completely, for local/vimeo videos. However, I modified a copy to use the youtube API. It takes a youtube url as the cue, as well as optionally a `Start Time` and `End Time` column. In the `Settings` column, you can set `submitOnDone` and `preventEarlySubmit` to false to make the trial act as a typical trial (i.e., you will get a done button that is controlled by typical minTime/maxTime behavior). As it is now, the submit button is invisible, and the trial submits when the video finishes. An early maxTime will still force an early submit, but if you set it to user, without changing the settings, it will appear to be a max time of the video length.

**Comment by adamblake** [comment]
Looks great Tyson --- cool idea to use the YouTube API and add those settings!

I saw the opportunity to throw in some comments on what each of the parameters was, and while I was in there I did some superficial reformatting/commenting of the PHP to make it match some of the other coding standards / improve readability. For reference, Tyson's commit was 5591d7c590929ac3d45d524cdce31b6feaa08ef1

**Comment by adamblake** [comment]
I did some testing and the YouTube trial works fantastically. The existence of the "video" trial type is a bit confusing because that trial type doesn't work the same ways (no start/end time, does not incorporate @TysonKerr's preventSubmit and submitOnDone settings). Unless either of you see a quick fix to make it passable, I propose we delete it and handle it in a different issue.

**Comment by TysonKerr** [comment]
I think we should have a local video trial type, even if it doesnt have settings for timing yet. One problem is that the function isLocal() doesn't seem to correctly identify local files. However, I tried switching the function to 
```php
function isLocal($path) {
    return !filter_var($path, FILTER_VALIDATE_URL);
}
```
and it seemed to correctly load both local files and youtube videos (presumably vimeo as well). Why dont we make this change and then leave video as a placeholder for now, and we can update it in the future?

**Comment by adamblake** [comment]
That's what I noticed as well. Nice fix

Can we add in a big warning at the top of the Video trial as well? E.g.
``` NOTE: This trial type has not been fully implemented yet. Please use the YouTube trial type for full functionality```
