### ISSUE TITLE
New shuffle functions break old grouping scheme

### ISSUE THREAD

**Issue by adamblake** [gikeymarcia/Collector#72]
In the old system, a setup like this would include all items that are grouped together, not caring about the group names:

item | shuffle
------------ | -------------
feature | banana
jacket | banana
wire | shuffle2
hanger | shuffle2
rack | banana
apple | banana

This would result in two banana groups, one with "feature, jacket" and the other with "rack, apple". With the new shuffle system, there is only one group of "feature, jacket, rack, apple". 

If this was intentional, and not a bug, then we need to update the sample stimuli and procedure sheets. Right now we have multiple passage that are included in a shuffle group with study trials. If this was unintentional, then we should add back in the consecutive grouping feature.

**Comment by gikeymarcia** [comment]
Feature, not a bug. Agree that we need to update the sample files. The reason this new shuffling hasn't been pushed live is because it will require some reeducation and the `/Tools/` folder will be the beginning of this.
