### ISSUE TITLE
on `dev`: isBlankLine declared more than once

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#78]
The way I coded the function `isBlankLine()` into `GetFromFile()` is wrong.  Currently each time you run `GetFromFile()` the function tries to define `isBlankLine()` again and PHP does not like this.  The solution is really simple but I am working on a side branch right now and this is a reminder to myself (or any of you willing to handle it) to fix this later.  Fixed way of declaring `isBlankLine()` from within another function so it only ever gets defined once:

```` PHP
#### decalre isBlankLine function the first time we run GetFromFile
if (!function_exists('isBlankLine')) {
    #### if an array is empty, all positions == "", return TRUE
    function isBlankLine ($array) {
        foreach ($array as $item) {
            if ($item != "") {
                return FALSE;
            }
        }
        return TRUE;
    }
}
````

**Comment by TysonKerr** [comment]
since isblankline() is only used once, why not just replace the function call with the actual foreach loop? That seems like a simpler solution, and a little bit faster as well. 

starting around line 343:

```php
$tOut = array_combine($keys, $line);
$isBlank= TRUE;
foreach ($tOut as $cell) {
    if ($cell !== '') {
        $isBlank = FALSE;
        break;
    }
}
if ($isBlank === FALSE) {
    $out[] = $tOut;
}
```

**Comment by gikeymarcia** [comment]
Agree.
