### ISSUE TITLE
RT does not work for FreeRecall [!!!!]

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#79]
Not sure how long this has been true but I was testing an experiment this morning and noticed that RT doesn't record for FreeRecall trials.  This should be hotfixed into master ASAP.

@TysonKerr might be able to shed some light on this issue.

**Comment by TysonKerr** [comment]
inside the free recall trial type, there is a closing </form> tag, which is excluding all the RT inputs that are created back in the main trial.php (we should probably rename these to be less confusing...).

**Comment by gikeymarcia** [comment]
My hero.
