### ISSUE TITLE
Allow `Instruct` trial type to use stimuli columns

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#81]
I will be making an update to the `Instruct` trial type that first checks if the `Item` # is > 1 and if it is then the `Instruct` will display the contents of the `Cue` column of the stimuli in use.

**Comment by TysonKerr** [comment]
Isn't that already possible, using the text "$cue"? I suppose this is not an obvious feature, but if we just give a few examples, they can also use this trick in other trial types, since the Text will always have $cue and $answer replaced with values from the stimuli file.

**Comment by gikeymarcia** [comment]
I'd like it to be more seamless and work similar to other trials.  The solution I'm thinking is actually very easy.
````PHP
if (($cue != '')
    && (trim($text) == '')
){
    $text = $cue;
}
````
Whenever a valid stimuli line is called the `Cue` will have some content and if that trial doesn't have anything set in `Text` then the `Cue` will be used.  This way we can still use your smart replacement stuff in `Text` if someone calls a valid stimuli but just wants to reference the cue inline (e.g., `In the next phase you are going to see a list of words about $cue`).  For those who want a straight display of the `Cue` contents they call a valid stimuli line and then leave the `Text` column empty.

I like this approach because those people who are used to using `Item` `0` and typing their instructions into `Text` can continue to do so but if they'd like to occasionally put their instruction text into the stimuli file then it is as simple as calling that row when using `Instruct` trial types.
