### ISSUE TITLE
$text not working in 'dev'

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#83]
Noticed this issue while testing dev using the demo condition. Whenever a JOL is used during post trial the program says the variable text is undefined.

@TysonKerr this is your domain.

**Comment by TysonKerr** [comment]
Should the default behavior be to assume that they wanted to use the "Text" column rather than the "Post 1 Text" column, or simply give them a $text variable with an empty string?

**Comment by gikeymarcia** [comment]
Post 1 Text

**Comment by gikeymarcia** [comment]
fixed in 72d8001dd16b910d7511ae6d3371381da0704994
