### ISSUE TITLE
required inputs in trials

### ISSUE THREAD

**Issue by TysonKerr** [gikeymarcia/Collector#89]
Currently, when the form submit button of a trial is clicked, some javascript records the trial and then submits the form.  If you add the required attribute to an input, and try to submit the form without filling out that input, the form will still get submitted, since the javascript submits the form even if the browser tries to validate the click.  It isn't too hard to handle form validation ourselves with more javascript, but someone using Collector without much javascript knowledge would probably just want to use the required attribute. And, in the Collector javascript, if you change the onclick function of the submit button, to remove the line that submits the form through JS, the browser will still submit the form properly, since a submit button was still clicked, and its native function of submitting the form hasn't been prevented.  However, if you do remove this extra code, and then click the submit button with a required input that hasn't been filled out, the JS will still hide the submit button, since the JS does not care whether the click will actually result in a submission or not.

One option would be to change the JS that records RT to happen on the form submit, rather than on the submit button click. After changing that, the code which submits the form could be removed, since the form is already in the process of getting submitted.

Alternatively, we could keep the onclick function of the submit button to record RT, but then use a separate function, on form submit, to handle hiding the precached content.

A different solution would be to add another class like forceNumeric, which just indicates that this input should be treated as required. Then, we could add some code in that detects if these classes are present in the form, and if so, disable the submit button until the inputs have a value !== "".

**Comment by adamblake** [comment]
Why don't we use valid HTML5 and just use Modernizr (http://modernizr.com/)
to handle the feature detection for us? We can cut out so much JS if we do
this.

Adam B. Blake, MA
Doctoral Student, Cognitive Psychology
UCLA Department of Psychology
1285 Franz Hall, Los Angeles, CA 90095
Memory and Lifespan Cognition Lab <http://castel.psych.ucla.edu>

**Comment by gikeymarcia** [comment]
@adamblake & @TysonKerr I'm beginning to think that we shouldn't even bother spending time coding for browsers that are quickly vanishing.  This is especially true for the mTurk population.  To see how much legacy support even matters I loaded up data from a HIT I collected 5 weeks ago on mTurk.  I found all unique user agent strings and ran each one through [this tool](https://www.whatismybrowser.com/developers/custom-parse?useragent=Mozilla%252F5.0+%2528X11%253B+Ubuntu%253B+Linux+x86_64%253B+rv%253A35.0%2529+Gecko%252F20100101+Firefox%252F35.0%250D%250A&SecurityID=18fbfb74e05d6a8801f98d19e1fd9fbf5dbb75aa&action_submit=Analyse+this+user+agent) to identify what we were looking at.

Summary of results (N=153):
95% of all users had modern fully HTML5 compliant browsers
* 53% of all users on Chrome 39 (most up to date chrome at the time)
* 33% of all users on firefox 34+ (most modern -1)
* 3% on IE 11/10 (HTML5 compliant)

Here are the ones I'm not sure are fully HTML5 compliant (counts)
* 2 Safari 8 iOS 8.1 -- iPad
* 2 Chrome 39 KitKat -- Galaxy Tab (I think these are actually fully HTML5 complaint)
* 1 Android Browser 4, Jelly Bean -- unknown device
* 1 Firefox 2.0, OS X (original)
* 1 IE 9

... upon more research it looks like [safari 8 is up to snuff](https://html5test.com/compare/browser/safari-8.0.html) as is [chrome 39](https://html5test.com/compare/browser/chrome-39.html) on the galaxy tab.  This means all of this extra work is basically to save (per every 150 participants) about 4 people.  Doesn't seem worthwhile. These stats will only get better with time as people continue moving into our bright HTML5 future.

**Comment by gikeymarcia** [comment]
We got off topic but an email from Paulo has reignited the idea that we should have a required input type feature.  He has written some script to accomplish this by intercepting the `#FormSubmitButton` but I think we can achieve this using the @TysonKerr forcedNumeric solution of adding JS that watches inputs with `class="forced"` then stops people from submitting until the inputs have been used.

Taking this one step further, if an input has `class="forced"` and a participants tries to submit without typing something we can read the procedure settings columns for `forced="you must respond"` and give the error specified in settings. If no error message is defined in setting we will use a generic "you must respond" error message.

OR, should we simply use the HTML5 `required` attribute which we currently break as is stated in Tyson's original comment above.  Example, `<input type="text" name="Response" value="" required>`

**Comment by TysonKerr** [comment]
To use html 5 validation, I think we just need to remove the javascript code that programmatically submits the form when the submit button is clicked.  That way, if the click is valid (no required inputs empty), then the natural function of the submit button will successfully submit the form. If a required input is left empty, then the html5 error will stop them.

I can also set up a few demo trial types, that demonstrate how to check if a text input is empty, and use that to disable/enable the submit button.  We already have some good css to grey-out the button and turn the cursor into a not-allowed symbol when the input has the disabled attribute. And, as an added bonus, if the submit button of a form is disabled, it seems that the Enter key is naturally prevented from submitting the form, so we dont even have to switch .noEnter on and off.

For most trial types that want to do something like this, they will probably give the same type of error/warning every time, so those can be built straight into the trial type. But, I can also make some examples that read in this message from settings/text, or use settings to determine if certain warning messages should appear at all.

**Comment by adamblake** [comment]
I'm feeling like next week I can go through all the HTML and convert it over to use HTML5 validation and use modernizr for fallback. It seems like we came more or less to this conclusion, right? Any objections, or perhaps someone has already started this?

**Comment by gikeymarcia** [comment]
It works now in dev!
