### ISSUE TITLE
Better user agent information

### ISSUE THREAD

**Issue by gikeymarcia** [gikeymarcia/Collector#90]
We should integrate [this github project](https://github.com/ua-parser/uap-php) into our code so we can give people much more useful information about which browser each person is coming from.

A demo is [at this page](http://uaparser.dmolsen.com/).

I think there is a way in git to install other repos as sub-modules which will make it very easy to keep their parsing library up to date on our end. So long as the function calls remain the same it will seamlessly keep improving as the user agent parser people push new code.

Here is sample code from their read me documentation

````PHP
require_once 'vendor/autoload.php';
use UAParser\Parser;

$ua = "Mozilla/5.0 (Macintosh; Intel Ma...";

$parser = Parser::create();
$result = $parser->parse($ua);

print $result->ua->family;            // Safari
print $result->ua->major;             // 6
print $result->ua->minor;             // 0
print $result->ua->patch;             // 2
print $result->ua->toString();        // Safari 6.0.2
print $result->ua->toVersion();       // 6.0.2

print $result->os->family;            // Mac OS X
print $result->os->major;             // 10
print $result->os->minor;             // 7
print $result->os->patch;             // 5
print $result->os->patchMinor;        // [null]
print $result->os->toString();        // Mac OS X 10.7.5
print $result->os->toVersion();       // 10.7.5

print $result->device->family;        // Other

print $result->toString();            // Safari 6.0.2/Mac OS X 10.7.5
print $result->originalUserAgent;     // Mozilla/5.0 (Macintosh; Intel Ma...
````

Stumbled onto this project from the discussion going on in isssue #89 about HTML5 support.

**Comment by gikeymarcia** [comment]
Project in the initial post requires composer and that seems complicated to setup for how we run Collector.  Might be better to base the new user agent information on [@GaretJax project, phpbrowscap](https://github.com/GaretJax/phpbrowscap) instead. They provide a standalone solution that'll be much better for our setup.

[Quick start guide for phpbrowscap](https://github.com/GaretJax/phpbrowscap/wiki/QuickStart)

**Comment by adamblake** [comment]
Yeah the first package would be overkill --- it requires some Symfony components and would add ~1.5MB to the size of the project. The second is much more concise.

What do we currently use this info for, and what other things do we want to use it for? I can put this in to have it available, but it would help to have a clear idea of what parts we need from it.

**Comment by TysonKerr** [comment]
I think the main things we would be interested in is desktop/mobile device, and if the browser they are using is html5 compliant. Other tidbits might be interesting, like OS for windows/mac users, but I think the critical feature is dekstop/mobile and html5

**Comment by adamblake** [comment]
I suppose this would go into Tools then. I'll add it in to make it available.

**Comment by adamblake** [comment]
Actually. I'm not sure what Tools does or is for. I'll branch this off and make it available and then work in the functions we want where we want them after I have a better handle on some of the newer stuff. Maybe we can talk about it on Monday night

**Comment by TysonKerr** [comment]
Well, if it could just create a column in session_start/finish, that would be pretty cool.

**Comment by adamblake** [comment]
Ah okay, that makes sense

**Comment by adamblake** [comment]
I haven't tested this yet, but it should work like a charm (except like in the fictional sense, and not the literal, superstitious sense...)

**Comment by gikeymarcia** [comment]
Tested this branch and ran into issues. See them on the pull request page https://github.com/gikeymarcia/Collector/pull/108

**Comment by adamblake** [comment]
Ok I looked into this and the problem is that the browscap project itself has major problems with memory management (https://github.com/browscap/browscap-php/issues/20). the Browscap project uses a far too large ini, which is what is causing the problems. I'll figure out an alternative or try to go through and cut out the auto-updating feature and use a smaller ini

**Comment by adamblake** [comment]
Fixed and tested this time. See commit 53321cc69 for more details
